language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - chmod +x gradlew
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/springboot1.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo setting에서 설정한 값
    secret_access_key: $AWS_SECRET_KEY #위와 동일

    bucket: springboot-youth-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private로 접근
    local_dir: deploy # before_deploy에서 생성한 디렉토리로
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: springboot-youth-build
    key: springboot1.zip

    bundle_type: zip
    application: springboot1

    deployment_group: springboot1-group

    region: ap-northeast-2
    wait-until-deployed: true




# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - boysoeng@naver.com